class AppLovConstants {
  static List<String> branches = const [
    'AMTA',
    'ASHOKENAGAR',
    'BADU',
    'BAGMORE',
    'BAGNAN',
    'BAGUIATI-KOLKATA',
    'BAKSHARA-HOWRAH',
    'BAKULTALA',
    'BALLY GOSWAMIPARA',
    'BALTIKURI-HOWRAH',
    'BAMUNGACHI',
    'BANIPUR',
    'BANITABLA',
    'BANKRA-HOWRAH',
    'BARASAT',
    'BARGACHIA',
    'BEGRI',
    'BELGHARIA',
    'BELIAGHATA BRIDGE',
    'BELLILIOUS ROAD',
    'BESU',
    'BINDHANNAGAR',
    'BILKANDA',
    'BONGAON',
    'CHANDPORE',
    'DAKSHIN JHAPARDA',
    'DAKSHIN JOYPUR',
    'DAKSHINESWAR',
    'DUM DUM-KOLKATA',
    'GARIA-KOLKATA',
    'HABRA',
  ];

  static List<String> products = const [
    'Car Loan',
    'Cash Loan',
    'Combo Car Loan',
    'Corporate Car Loan',
    'Corporate Home Loan',
    'Educational Loan',
    'Housing Loan',
    'Pensioner Loan',
    'Property Loan',
    'Rent Loan',
    'UCO Survodaya Loan Scheme',
    'Two Wheeler Loan',
    'UCO Electric Vehicle Loan',
    'UCO Electric Vehicle EV Loan',
    'UCO Elite Two Wheeler Loan',
  ];
}
