import 'package:newsee/Model/news_modal.dart';

List<News> news_collections = [
  News(
    "news_1",
    "A new AI model improves diagnosis accuracy by 30%.",
    "AI Breakthrough in Healthcare",
    "Technology",
    true,
    ["AI", "Healthcare", "Innovation"],
  ),
  News(
    "news_2",
    "The team clinched the title in a thrilling match.",
    "Team Wins Championship",
    "Sports",
    false,
    ["Football", "Championship"],
  ),
  News(
    "news_3",
    "The new government promises reforms.",
    "Election Results Announced",
    "Politics",
    true,
    ["Election", "Politics"],
  ),
  News(
    "news_4",
    "The movie grossed \$1 billion in a week.",
    "Blockbuster Movie Release",
    "Entertainment",
    false,
    ["Movie", "Box Office"],
  ),
  News(
    "news_5",
    "Vaccine protects against multiple variants.",
    "Vaccine Breakthrough",
    "Health",
    true,
    ["Vaccine", "Health"],
  ),
  News(
    "news_6",
    "Quantum computers solve complex problems faster.",
    "Quantum Computing Advances",
    "Technology",
    false,
    ["Quantum", "Tech"],
  ),
  News(
    "news_7",
    "The player is out for the season.",
    "Star Athlete Injured",
    "Sports",
    true,
    ["Injury", "Sports"],
  ),
  News(
    "news_8",
    "Policy aims to cut emissions by 50%.",
    "New Policy on Climate Change",
    "Politics",
    false,
    ["Climate", "Policy"],
  ),
  News(
    "news_9",
    "Artists win big at the gala.",
    "Music Awards 2025",
    "Entertainment",
    true,
    ["Music", "Awards"],
  ),
  News(
    "news_10",
    "Campaign promotes therapy access.",
    "Mental Health Awareness",
    "Health",
    false,
    ["Mental Health", "Wellness"],
  ),
  News(
    "news_11",
    "Latest smartphone features a 200MP camera.",
    "New Smartphone Launch",
    "Technology",
    true,
    ["Smartphone", "Tech"],
  ),
  News(
    "news_12",
    "Athletes break world records.",
    "Olympics 2024 Highlights",
    "Sports",
    false,
    ["Olympics", "Records"],
  ),
  News(
    "news_13",
    "Leaders discuss global peace.",
    "International Summit Held",
    "Politics",
    true,
    ["Summit", "Politics"],
  ),
  News(
    "news_14",
    "Platform offers exclusive content.",
    "New Streaming Platform",
    "Entertainment",
    false,
    ["Streaming", "Entertainment"],
  ),
  News(
    "news_15",
    "Wearables track health metrics.",
    "Fitness Tech Innovations",
    "Health",
    true,
    ["Fitness", "Health"],
  ),
  News(
    "news_16",
    "Blockchain ensures secure transactions.",
    "Blockchain Adoption Grows",
    "Technology",
    false,
    ["Blockchain", "Security"],
  ),
  News(
    "news_17",
    "The stadium cost \$500 million.",
    "New Stadium Opens",
    "Sports",
    true,
    ["Stadium", "Sports"],
  ),
  News(
    "news_18",
    "Trade deal boosts economy.",
    "Trade Agreement Signed",
    "Politics",
    false,
    ["Trade", "Economy"],
  ),
  News(
    "news_19",
    "The wedding was a star-studded event.",
    "Celebrity Wedding Buzz",
    "Entertainment",
    true,
    ["Celebrity", "Wedding"],
  ),
  News(
    "news_20",
    "Diet claims rapid weight loss.",
    "New Diet Trend",
    "Health",
    false,
    ["Diet", "Wellness"],
  ),
  News(
    "news_21",
    "Hackers target major corporations.",
    "Cybersecurity Threats Rise",
    "Technology",
    true,
    ["Cybersecurity", "Tech"],
  ),
  News(
    "news_22",
    "Esports prize pool reaches \$10 million.",
    "Esports Tournament Success",
    "Sports",
    false,
    ["Esports", "Tournament"],
  ),
  News(
    "news_23",
    "Investigation reveals corruption.",
    "Political Scandal Uncovered",
    "Politics",
    true,
    ["Scandal", "Politics"],
  ),
  News(
    "news_24",
    "Fans debate the shocking twist.",
    "TV Show Finale Shocks Fans",
    "Entertainment",
    false,
    ["TV", "Finale"],
  ),
  News(
    "news_25",
    "Initiative targets rural healthcare.",
    "Global Health Initiative",
    "Health",
    true,
    ["Health", "Initiative"],
  ),
  News(
    "news_26",
    "AI predicts market trends with high accuracy.",
    "AI in Finance",
    "Technology",
    false,
    ["AI", "Finance"],
  ),
  News(
    "news_27",
    "Underdog team reaches finals.",
    "Surprise in League Playoffs",
    "Sports",
    true,
    ["Football", "Playoffs"],
  ),
  News(
    "news_28",
    "New law sparks protests.",
    "Controversial Legislation Passed",
    "Politics",
    false,
    ["Law", "Protests"],
  ),
  News(
    "news_29",
    "Singer drops surprise album.",
    "New Music Release",
    "Entertainment",
    true,
    ["Music", "Album"],
  ),
  News(
    "news_30",
    "Study links exercise to longevity.",
    "Fitness and Longevity",
    "Health",
    false,
    ["Fitness", "Health"],
  ),
  News(
    "news_31",
    "Self-driving cars hit the market.",
    "Autonomous Vehicle Launch",
    "Technology",
    true,
    ["Autonomous", "Tech"],
  ),
  News(
    "news_32",
    "Rookie wins major tournament.",
    "Golf Star Emerges",
    "Sports",
    false,
    ["Golf", "Tournament"],
  ),
  News(
    "news_33",
    "Talks aim to resolve conflict.",
    "Peace Negotiations Begin",
    "Politics",
    true,
    ["Peace", "Politics"],
  ),
  News(
    "news_34",
    "Documentary wins top award.",
    "Film Festival Highlights",
    "Entertainment",
    false,
    ["Documentary", "Film"],
  ),
  News(
    "news_35",
    "New therapy shows promise.",
    "Breakthrough in Cancer Treatment",
    "Health",
    true,
    ["Cancer", "Health"],
  ),
  News(
    "news_36",
    "AR glasses revolutionize gaming.",
    "Augmented Reality Advances",
    "Technology",
    false,
    ["AR", "Gaming"],
  ),
  News(
    "news_37",
    "Marathon sets participation record.",
    "City Marathon Success",
    "Sports",
    true,
    ["Marathon", "Sports"],
  ),
  News(
    "news_38",
    "Budget plan faces criticism.",
    "National Budget Announced",
    "Politics",
    false,
    ["Budget", "Politics"],
  ),
  News(
    "news_39",
    "Reality show breaks records.",
    "New Reality TV Hit",
    "Entertainment",
    true,
    ["TV", "Reality"],
  ),
  News(
    "news_40",
    "Air purifiers reduce allergies.",
    "Indoor Air Quality Improved",
    "Health",
    false,
    ["Health", "Allergies"],
  ),
  News(
    "news_41",
    "Satellite network expands internet.",
    "Global Internet Access",
    "Technology",
    true,
    ["Satellite", "Tech"],
  ),
  News(
    "news_42",
    "Team signs star player.",
    "Major Transfer in Soccer",
    "Sports",
    false,
    ["Soccer", "Transfer"],
  ),
  News(
    "news_43",
    "New alliance strengthens ties.",
    "Diplomatic Agreement Signed",
    "Politics",
    true,
    ["Diplomacy", "Politics"],
  ),
  News(
    "news_44",
    "Theater production sold out.",
    "Broadway Show Success",
    "Entertainment",
    false,
    ["Theater", "Broadway"],
  ),
  News(
    "news_45",
    "Yoga gains popularity.",
    "Mindfulness Trend Grows",
    "Health",
    true,
    ["Yoga", "Wellness"],
  ),
  News(
    "news_46",
    "Robot assists in surgeries.",
    "Robotics in Medicine",
    "Technology",
    false,
    ["Robotics", "Healthcare"],
  ),
  News(
    "news_47",
    "Skier wins gold medal.",
    "Winter Sports Triumph",
    "Sports",
    true,
    ["Skiing", "Sports"],
  ),
  News(
    "news_48",
    "Tax reform sparks debate.",
    "New Tax Policy Proposed",
    "Politics",
    false,
    ["Tax", "Policy"],
  ),
  News(
    "news_49",
    "Game show returns with twist.",
    "TV Game Show Revival",
    "Entertainment",
    true,
    ["TV", "Game Show"],
  ),
  News(
    "news_50",
    "Plant-based diet gains traction.",
    "Veganism on the Rise",
    "Health",
    false,
    ["Diet", "Vegan"],
  ),
];
